# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0380ab91c381f922f96b428240d0edd275ae24a9d9ea5bbb8543e37cfd0810a9c86f7a4d9b1f7412d5f365b6027f648bee944e9078e3e88712b9289ac9bf99b4

test:
  secret_key_base: a797148e7589e14065c56d5e53958a9fdf7a04263a1e98e630b3a227525971400d9e960c9f9f208973f3fa730e9bf534c778f1488a882159530e38f6b87c26e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
